Repository ViorelMocanu/digital-resources, pull requests merged in 2023-10, with the labels that each got.

#66 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#74 fix: lockfile for deploy
  pnpm-lock.yaml
Labels: bug

#75 feat: implement a simpler breadcrumbs component
  src/components/Breadcrumbs.astro
  src/components/Header.astro
  src/config.ts
  src/layouts/Layout.astro
  src/pages/404.astro
  src/pages/[section]/[...page].astro
  src/pages/[section]/[category]/[...page].astro
  src/pages/[section]/[category]/[subcategory]/[...page].astro
  src/pages/confidentialitate.astro
  src/pages/contact.astro
  src/pages/cookies.astro
  src/pages/faq.astro
  src/pages/resurse/[slug].astro
  src/pages/resurse/index.astro
  src/pages/taguri/[slug].astro
  src/pages/taguri/index.astro
  src/pages/termeni-si-conditii.astro
Labels: enhancement, refactor

#79 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#80 Create humans.txt
  public/humans.txt
  src/layouts/Layout.astro
Labels: documentation

#81 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#82 Create Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#83 Create greetings.yml
  .github/workflows/greetings.yml
Labels: ops

#84 Create supporting security pages
  SECURITY.md
  public/.well-known/security.txt
  src/pages/hall-of-fame.astro
  src/pages/politica-de-securitate.astro
Labels: security, content

#86 Edit README.md + .env
  .env.example
  .gitignore
  README.md
  astro.config.mjs
  src/config.ts
Labels: documentation, enhancement

#104 Add some content
  astro.config.mjs
  src/content/config.ts
  src/content/resources/complete-beginners-guide-to-information-architecture.md
  src/content/resources/how-does-the-web-work.md
  src/content/resources/img/complete-beginners-guide-to-information-architecture.jpg
  src/content/resources/img/og-the-odin-project.png
  src/content/resources/odin-project-web-development.md
  src/content/resources/resilient-web-design.md
  src/pages/[section]/[...page].astro
  src/pages/[section]/[category]/[...page].astro
  src/pages/[section]/[category]/[subcategory]/[...page].astro
  src/pages/resurse/[slug].astro
  src/style/style.scss
Labels: design, content

#105 fix: deploy and dependency issues
  .gitignore
  astro.config.mjs
  src/config.ts
  src/layouts/Layout.astro
  src/layouts/LayoutMarkdown.astro
Labels: bug

#108 chore: update dependencies
  package.json
  pnpm-lock.yaml
Labels: ops

#109 feat: add resource-specific emojis based on type
  src/components/ResourceList.astro
  src/config.ts
  src/pages/resurse/[slug].astro
  src/style/style.scss
Labels: enhancement, design

#112 feat: add Vitests + typesafe components via CursorIDE & CodiumAI
  .github/dependabot.yml
  package.json
  pnpm-lock.yaml
  src/components/Breadcrumbs.astro
  src/components/Footer.astro
  src/components/Header.astro
  src/components/MarkdownTOC.astro
  src/components/Message.astro
  src/components/Pagination.astro
  src/components/ResourceFilter.astro
  src/components/ResourceList.astro
  src/components/ResourceLocationList.astro
  src/components/ResourceTOC.astro
  src/components/ResourceTagList.astro
  src/components/ResponsiveImage.astro
  src/config.ts
  src/layouts/Layout.astro
  src/layouts/LayoutMarkdown.astro
  src/pages/resurse/[slug].astro
  src/utils/email.ts
  src/utils/resourceMeta.ts
  src/utils/urlHelpers.ts
  test/basic.test.ts
  test/resourceMeta.test.ts
  test/urlHelpers.test.ts
Labels: documentation, ops

#118 Get sorted items feature
  src/components/Footer.astro
  src/utils/contentCollections.ts
  src/utils/getSortedItems.ts
Labels: enhancement, good first issue

#127 Get sorted items feature
  src/components/Footer.astro
  src/pages/[section]/[...page].astro
  src/utils/getSortedItems.ts
Labels: enhancement

#123 Add Analytics (#39)
  .github/workflows/snyk-security.yml
  .husky/pre-commit
  .markdownlint.json
  .prettierignore
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/components/Analytics.astro
  src/components/Footer.astro
  src/components/ResponsiveImage.astro
  src/config.ts
  src/layouts/Layout.astro
  src/layouts/LayoutMarkdown.astro
  src/pages/README.md
  src/pages/[section]/[...page].astro
  src/utils/getSortedItems.ts
  test/getSortedItems.test.ts
Labels: enhancement

#128 fix: hotfix - env debugging
  astro.config.mjs
  src/components/Analytics.astro
  src/config.ts
  src/layouts/Layout.astro
  src/utils/getSortedItems.ts
Labels: ops

#139 chore(getSortedItems): fix return type
  package.json
  pnpm-lock.yaml
  src/components/ResourceList.astro
  src/components/ResourceLocationList.astro
  src/components/ResourceTOC.astro
  src/components/ResourceTagList.astro
  src/config.ts
  src/pages/[section]/[...page].astro
  src/pages/[section]/[category]/[...page].astro
  src/pages/[section]/[category]/[subcategory]/[...page].astro
  src/pages/resurse/[slug].astro
  src/utils/getSortedItems.ts
  tsconfig.json
Labels: bug, refactor
