Repository ViorelMocanu/digital-resources, pull requests merged in 2023-11, with the labels that each got.

#144 chore: rename types and update deps
  package.json
  pnpm-lock.yaml
  src/components/ResourceList.astro
  src/components/ResourceLocationList.astro
  src/components/ResourceTOC.astro
  src/config.ts
Labels: ops

#149 chore: update deps
  package.json
  pnpm-lock.yaml
Labels: dependencies

#152 fix(all): typescript
  .husky/commit-msg
  .husky/functions.sh
  .husky/post-checkout
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/components/Analytics.astro
  src/components/Breadcrumbs.astro
  src/components/Header.astro
  src/components/ResourceFilter.astro
  src/components/ResourceTOC.astro
  src/components/ResponsiveImage.astro
  src/config.ts
  src/layouts/Layout.astro
  src/layouts/LayoutMarkdown.astro
  src/pages/[section]/[...page].astro
  src/pages/[section]/[category]/[...page].astro
  src/pages/[section]/[category]/[subcategory]/[...page].astro
  src/pages/cauta.astro
  src/pages/resurse/[slug].astro
  src/pages/resurse/index.astro
  src/utils/getSortedItems.ts
Labels: bug, documentation, enhancement, ops, dependencies, refactor
